WITH CTE AS (select 
STARTED_AT
,TRY_TO_TIMESTAMP_NTZ(STARTED_AT) AS STARTED_AT2
,DATE(TRY_TO_TIMESTAMP_NTZ(STARTED_AT)) AS DATE_STARTED_AT
,HOUR(TRY_TO_TIMESTAMP_NTZ(STARTED_AT)) AS HOUR_STARTED_AT
,DAYNAME(TRY_TO_TIMESTAMP_NTZ(STARTED_AT)) AS DAYNAME_STARTED_AT
, CASE WHEN 
DAYNAME(TRY_TO_TIMESTAMP_NTZ(STARTED_AT)) IN ('Sat', 'Sun')
THEN 'WEEKEND'
ELSE 'BUSINESSDAY'
END AS DAY_TYPE,
MONTH(TRY_TO_TIMESTAMP_NTZ(STARTED_AT)) AS MONTH_STARTED_AT
, CASE WHEN 
MONTH(TRY_TO_TIMESTAMP_NTZ(STARTED_AT)) IN (12,1,2)
THEN 'WINTER'
WHEN MONTH(TRY_TO_TIMESTAMP_NTZ(STARTED_AT)) IN (3,4,5)
THEN 'SPRING'
WHEN MONTH(TRY_TO_TIMESTAMP_NTZ(STARTED_AT)) IN (6,7,8)
THEN 'SUMMER'
ELSE 'AUTUMN'
END AS STATION_OF_YEAR
  FROM {{ source('demo', 'bike') }}
 WHERE STARTED_AT != 'started_at')
select * FROM CTE
